[
  ./config/home-manager.nix
  ./config/networking.nix
  ./config/system.nix
  ./config/users/novenary.nix
  ./config/workstation
  ./hosts/Akatsuki/configuration.nix
  ./hosts/Akatsuki/ddcci.nix
  ./hosts/Akatsuki/hardware-configuration.nix
  ./hosts/Akatsuki/jellyfin.nix
  ./hosts/Akatsuki/metalfan.nix
  ./services/metalfan
  ./system_profile.nix
]
