[
  ./common/networking.nix
  ./common/system.nix
  ./common/users
  ./common/workstation
  ./hosts/Akatsuki/configuration.nix
  ./hosts/Akatsuki/ddcci.nix
  ./hosts/Akatsuki/hardware-configuration.nix
  ./hosts/Akatsuki/jellyfin.nix
  ./hosts/Akatsuki/metalfan.nix
  ./services/metalfan
  ./system_profile.nix
]
