[nixos-21_11]
src.github_tag = "NixOS/nixpkgs"
src.branch = "nixos-21.11"
fetch.github = "NixOS/nixpkgs"

[nixos-unstable]
src.git = "https://github.com/NixOS/nixpkgs"
src.branch = "nixos-unstable"
fetch.github = "NixOS/nixpkgs"

[nixpkgs-lib]
src.git = "https://github.com/nix-community/nixpkgs.lib"
fetch.github = "nix-community/nixpkgs.lib"

[nvfetcher]
src.git = "https://github.com/berberman/nvfetcher"
fetch.github = "berberman/nvfetcher"
