# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  nixos-21_11 = {
    pname = "nixos-21_11";
    version = "2128d0aa28edef51fd8fef38b132ffc0155595df";
    src = fetchFromGitHub ({
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "2128d0aa28edef51fd8fef38b132ffc0155595df";
      fetchSubmodules = false;
      sha256 = "sha256-hO9X4PvxkSLMQnGGB7tOrKPwufhLMiNQMNXNwzLqneo=";
    });
  };
  nixos-unstable = {
    pname = "nixos-unstable";
    version = "48d63e924a2666baf37f4f14a18f19347fbd54a2";
    src = fetchFromGitHub ({
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "48d63e924a2666baf37f4f14a18f19347fbd54a2";
      fetchSubmodules = false;
      sha256 = "sha256-D3VuWLdnLmAXIkooWAtbTGSQI9Fc1lkvAr94wTxhnTU=";
    });
  };
  nixpkgs-lib = {
    pname = "nixpkgs-lib";
    version = "e9d39d954b6fa4fc5bd56c9f5007cc37f3dcad76";
    src = fetchFromGitHub ({
      owner = "nix-community";
      repo = "nixpkgs.lib";
      rev = "e9d39d954b6fa4fc5bd56c9f5007cc37f3dcad76";
      fetchSubmodules = false;
      sha256 = "sha256-bL1sdn3F+DjeIo2c4AKQmVsrk6KMNUfSVeER+72tRHk=";
    });
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "9f2cb15c4668859312b6a854d79ad753d5b98b03";
    src = fetchFromGitHub ({
      owner = "berberman";
      repo = "nvfetcher";
      rev = "9f2cb15c4668859312b6a854d79ad753d5b98b03";
      fetchSubmodules = false;
      sha256 = "sha256-xEhhLmuy4FnT4Zdkf3epPX9T3xqn59yERCsicG4IEyM=";
    });
  };
}
