[
  ./config/colors.nix
  ./config/misc.nix
  ./config/workstation/foot.nix
  ./config/workstation/gtk.nix
  ./config/workstation/sway
  ./config/workstation/sway/wlsunset.nix
  ./config/workstation/telegram.nix
  ./config/workstation/xcursor.nix
  ./config/zsh
  ./config/zsh/dircolors.nix
  ./hosts/Akatsuki/mpd.nix
]
